spring:
  application:
    name: CompletableFuture
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      password: system
      username: system
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        ddl-auto: create
