spring:
  application:
    name: CompletableFuture
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      password: system
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: system
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQLDialect

